### ISSUE TITLE
Running without CUDA (CPU only)

### ISSUE THREAD

**Issue by martiningram** [endernewton/tf-faster-rcnn#25] opened 2017-03-22 05:31 UTC
Hi,

I am just wondering if there is a way of running this model on a machine without a GPU? Running `make` attempts to find CUDA.

Thanks!

**Comment by endernewton** [comment] 2017-03-28 20:21
you can install cuda without gpu. haven't tried that though.

**Comment by jwnsu** [comment] 2017-03-28 21:08
Current codes run fine on CPU, need to change NMS mode to CPU only.

**Comment by endernewton** [comment] 2017-03-28 21:16
Ahh I see. thanks for the update. Closing.

**Closed by endernewton** 2017-03-28 21:16 UTC

**Comment by guotong1988** [comment] 2017-04-01 02:14
@jwnsu Could you please describe how to run it on CPU in detail? Thank you.
The start script is most important.

**Comment by guotong1988** [comment] 2017-04-01 02:48
Finally it shows:
`iter: 20 / 70000, total loss: 2.201489`

You need to:
change `nms_wrapper.py`.
change `setup.py`.
`make` at `./lib`.
put the data at `tf-faster-rcnn-master/data/VOCdevkit2007/VOC2007`
and here are the parameters:

```
  parser.add_argument('--cfg', dest='cfg_file',
                      help='optional config file',
                      default="/home/gt/tf-faster-rcnn-master/experiments/cfgs/vgg16.yml", type=str)
  parser.add_argument('--weight', dest='weight',default="/home/gt/tf-faster-rcnn-master/vgg16.ckpt",
                      help='initialize with pretrained model weights',
                      type=str)
  parser.add_argument('--imdb', dest='imdb_name',
                      help='dataset to train on',
                      default='voc_2007_trainval', type=str)
  parser.add_argument('--imdbval', dest='imdbval_name',
                      help='dataset to validate on',
                      default='voc_2007_trainval', type=str)
  parser.add_argument('--iters', dest='max_iters',
                      help='number of iterations to train',
                      default=70000, type=int)
  parser.add_argument('--net', dest='net',
                      help='vgg16 or res101',
                      default='vgg16', type=str)
```

**Comment by bhack** [comment] 2017-04-01 22:35
@guotong1988 Can you open a PR with a CPU option.. could be useful for users with GPU memory limits..

**Comment by caunion** [comment] 2017-04-27 02:46
I think you can add a parameter in commandline to force CPU. i.e. 

`./experiments/scripts/train_faster_rcnn.sh 1 pascal_voc vgg16 **USE_GPU_NMS False**`

**Comment by Dinkz** [comment] 2017-05-08 11:56
@guotong1988 
Can I know what change you did inside setup.py ?

**Comment by HiZhongfei** [comment] 2017-05-23 11:48
@guotong1988  
what  change ocured in nms_wrapper.py & setup.py?

**Comment by dancsalo** [comment] 2017-05-23 13:18
@caunion's comment contains all that you need to do to force CPU. No need to change nms_wrapper.py or setup.py. Just tried it myself!

**Comment by joeliven** [comment] 2017-06-05 23:27
@endernewton great implementation of Faster RCNN. Really appreciate it. 
Question though: I can't get this to work on CPU only. I've read through the above and tried those suggestions but can't seem to get it to work. @caunion @guotong1988 has anybody had success in making this work on CPU? If so, how?
Thanks in advance for any suggestions. Much appreciated!

**Comment by endernewton** [comment] 2017-06-06 00:41
So what is the error msg?

**Comment by riadhayachi** [comment] 2017-07-13 10:00
use this command 
./tools/demo.py cpu

**Comment by qrfaction** [comment] 2017-10-22 09:27
@riadhayachi  
demo.py: error: unrecognized arguments: CPU

**Comment by grimfix** [comment] 2017-11-30 13:09
The nms_wrapper.py checks the model.config structure if USE_GPU_NMS flag is found. So, no need to change anything in nms_wrapper.py. Just set the flag in demo.py. Add the line `cfg.USE_GPU_NMS =False` after line 114 in demo.py. This worked for me.

**Comment by hang81** [comment] 2018-03-21 23:08
Hi,

I would like to deploy this great project without GPU (I do not have GPU on my laptop). However, after reading all the threads above, I am still stuck in Step 3 as described on the project page w.r.t  Installation:

> 3. Build the Cython modules
> make clean
> make
> cd ..

It throws the error message as follows,

> python setup.py build_ext --inplace --compiler=mingw64
> Traceback (most recent call last):
>  File "setup.py", line 55, in <module>
>    CUDA = locate_cuda()
>  File "setup.py", line 43, in locate_cuda
>    raise EnvironmentError('The nvcc binary could not be '
>OSError: The nvcc binary could not be located in your $PATH. Either add it to your path, or set >$CUDAHOME
>Makefile:2: recipe for target 'all' failed
>mingw32-make: *** [all] Error 1

Any idea/suggestion how to proceed?

Thanks.

Regards,

Hang

**Comment by joeliven** [comment] 2018-03-26 06:17
@hang81 try this:
```
def customize_compiler_for_nvcc(self):
    """inject deep into distutils to customize how the dispatch
    to gcc/nvcc works.

    If you subclass UnixCCompiler, it's not trivial to get your subclass
    injected in, and still have the right customizations (i.e.
    distutils.sysconfig.customize_compiler) run on it. So instead of going
    the OO route, I have this. Note, it's kind of like a weird functional
    subclassing going on."""

    # save references to the default compiler_so and _comple methods
    default_compiler_so = self.compiler_so
    super = self._compile

    # now redefine the _compile method. This gets executed for each
    # object but distutils doesn't have the ability to change compilers
    # based on source extension: we add it.
    def _compile(obj, src, ext, cc_args, extra_postargs, pp_opts):
        print(extra_postargs)
        postargs = extra_postargs['gcc']

        super(obj, src, ext, cc_args, postargs, pp_opts)
        # reset the default compiler_so, which we might have changed for cuda
        self.compiler_so = default_compiler_so

    # inject our redefined _compile method into the class
    self._compile = _compile


# run the customize_compiler
class custom_build_ext(build_ext):
    def build_extensions(self):
        customize_compiler_for_nvcc(self.compiler)
        build_ext.build_extensions(self)

ext_modules = [
    Extension(
        "utils.cython_bbox",
        ["utils/bbox.pyx"],
        extra_compile_args={'gcc': ["-Wno-cpp", "-Wno-unused-function"]},
        include_dirs = [numpy_include]
    ),
    Extension(
        "utils.cython_nms",
        ["utils/nms.pyx"],
        extra_compile_args={'gcc': ["-Wno-cpp", "-Wno-unused-function"]},
        include_dirs = [numpy_include]
    ),
    Extension(
        "nms.cpu_nms",
        ["nms/cpu_nms.pyx"],
        extra_compile_args={'gcc': ["-Wno-cpp", "-Wno-unused-function"]},
        include_dirs = [numpy_include]
    )
]

setup(
    name='tf_faster_rcnn',
    ext_modules=ext_modules,
    # inject our custom trigger
    cmdclass={'build_ext': custom_build_ext},
)
```
This is what I used when debugging locally on my machine that has cpu only. I named it setup_cpu.py and had it next to the included setup.py and used one or the other based on if gpu machine or cpu only machine. Note this does not include the import lines bc some are custom my specific project, but...for me this worked for running the setup code for cython extensions when no gpu avail. Hope it helps!
Joel

**Comment by lshe7842** [comment] 2018-05-10 06:58
This works thanks @joeliven. But I think you need to remove the 2nd Extension since 'nms.pyx' doesn't exist, at least in my repo.

**Comment by joeliven** [comment] 2018-05-14 03:39
No problem @lshe7842 , glad it worked for you!

**Comment by gepengxu** [comment] 2018-05-16 06:10
@joeliven

**Comment by DAA233** [comment] 2018-06-05 14:22
Based on @shuang1330‘s answer in #72, what I have done to support CPU on Mac OS:
- `lib/setup.py`: replace 'raise EnvironmentError' to `pass` to prevent the no CUDA environment error. Comment the block of `Extension('nms.gpu_nms'..)` to complile with out `nms.gpu_nms`.

**Comment by DAA233** [comment] 2018-06-05 14:26
Based on @shuang1330‘s answer in #72, what I have done to support running with CPU on Mac OS:
- `lib/setup.py`: replace `raise EnvironmentError` to `pass` to prevent the no CUDA environment error; comment the block of `Extension('nms.gpu_nms'..)` to complile with out `nms.gpu_nms`.
- `lib/model/config.py`: change `__C.USE_GPU_NMS = True` to `__C.USE_GPU_NMS = False`.
- `lib/model/nms_wrapper`: comment `from nms.gpu_nms import gpu_nms` to prevent import error.

**Comment by Medj9** [comment] 2018-07-09 10:09
hi , i have a issue in running demo.py on cpu in ubuntu 16.04, 
tensorflow version- 1.2
python 3.5
when i gave path to the model,it is present 
error shows in saver.restore(sess, tfmodel)

Error:
Traceback (most recent call last):
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
    return fn(*args)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
    status, run_metadata)
  File "/usr/lib/python3.5/contextlib.py", line 66, in __exit__
    next(self.gen)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_529 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_529/tensor_names, save/RestoreV2_529/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/tf-faster-rcnn/tools/demo.py", line 155, in <module>
    saver.restore(sess, tfmodel)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: Read less bytes than requested
	 [[Node: save/RestoreV2_529 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_529/tensor_names, save/RestoreV2_529/shape_and_slices)]]

Caused by op 'save/RestoreV2_529', defined at:
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/tf-faster-rcnn/tools/demo.py", line 153, in <module>
    saver = tf.train.Saver()
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/kpit/Desktop/Faster_Rcnn_Tensorflow/Virtualenv_tensorflow/tensorflow/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

OutOfRangeError (see above for traceback): Read less bytes than requested
	 [[Node: save/RestoreV2_529 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save/Const_0_0, save/RestoreV2_529/tensor_names, save/RestoreV2_529/shape_and_slices)]]

**Comment by Nioolek** [comment] 2018-07-18 12:17
I used the method commented by grimfix on 30 Nov 2017 , and it worked without gpu.The comment is on the front.

**Comment by smallnine9** [comment] 2018-07-30 01:17
@Nioolek  Do you use `bash make.sh`?

**Comment by smallnine9** [comment] 2018-07-30 02:13
@endernewton Alright，I find this issue is about tf-faster-rcnn, but in pytorch-faster-rcnn, we should use` bash make.sh`,but without GPU,without nvcc, that would report error,how to solve it?

**Comment by earthmover-jimp** [comment] 2020-03-29 09:17
Can it run under python3.6？
