### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Usernamezhx** [endernewton/tf-faster-rcnn#232] opened 2017-10-24 07:33 UTC
first of all .thanks for your code.
this is my setup.py:
`extra_compile_args={'gcc': ["-Wno-unused-function"],
                            'nvcc': ['-arch=sm_35',
                                     '--ptxas-options=-v',
                                     '-c',
                                     '--compiler-options',
                                     "'-fPIC'"]}`
I change the -arch=sm_35 since my GPU is k40.
but when i run the `CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py`
it will throw that:
2017-10-24 15:32:56.795543: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 15:32:56.795608: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 15:32:56.795621: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 15:32:56.795629: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 15:32:56.795639: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-10-24 15:33:11.362101: I tensorflow/core/common_runtime/gpu/gpu_device.cc:955] Found device 0 with properties: 
name: Tesla K40c
major: 3 minor: 5 memoryClockRate (GHz) 0.745
pciBusID 0000:c4:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
2017-10-24 15:33:11.362242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:976] DMA: 0 
2017-10-24 15:33:11.362473: I tensorflow/core/common_runtime/gpu/gpu_device.cc:986] 0:   Y 
2017-10-24 15:33:11.362503: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1045] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40c, pci bus id: 0000:c4:00.0)
Segmentation fault (core dumped)

**Comment by endernewton** [comment] 2017-10-24 13:59
hmm just making sure this is caused by gpu, maybe first try gpu nms false?

**Comment by Usernamezhx** [comment] 2017-10-25 02:01
thanks for your reply !when i first run the `CUDA_VISIBLE_DEVICES=${GPU_ID} ./tools/demo.py` it will show that:nms false.Because i forget to make in the /lib .after that it did not occurr

**Comment by endernewton** [comment] 2017-10-27 03:20
closing, thanks for the datapoint!

**Closed by endernewton** 2017-10-27 03:20 UTC

**Comment by chunkypilu** [comment] 2018-02-25 13:28
I am getting this error on HPC.
Please check: 
http://community.pbspro.org/t/segmentation-fault-core-dumped-python/880

**Comment by chunkypilu** [comment] 2018-02-25 13:32
@endernewton ,I am getting this error while running my code on HPC.
Please check:
http://community.pbspro.org/t/segmentation-fault-core-dumped-python/880
